### ISSUE TITLE
Fedora 28

### ISSUE THREAD

**Issue by MrSampson** [Cybolic/rpmspec-bitwig-studio#1]
In the comments you write that for Fedora28 two of the libavcodec files should be replaced by the comp-ffmpeg28 package.

Do you mean to replace the libavformat.so.56 and libavcodec.so.56 lines with symbolic links to the files in /usr/lib64 ?

**Comment by Cybolic** [comment]
I'm not using Fedora anymore and I never upgraded to 28, so I can't verify that it'll work, but my understanding was that `libavformat.so.56` and `libavcodec.so.56` are included in `comp-ffmpeg28` and the lines 44 to 52 shouldn't be necessary at all if the `comp-ffmpeg28` is installed.
